services:
  order-service:
    build: .
    image: inno-order-service
    container_name: order-service-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      SERVER_PORT: 8080
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/${POSTGRES_DB}
      SPRING_DATA_REDIS_HOST: order-redis
      SPRING_DATA_REDIS_PORT: 6379
      AUTH_JWKS_URI: http://auth-service:8080/.well-known/jwks.json
      USER_SERVICE_URL: http://user-service:8080
    depends_on:
      order-postgres:
        condition: service_healthy
      order-redis:
        condition: service_healthy
    networks:
      - inno-net
      - order-internal

  order-postgres:
    image: postgres:16
    container_name: order-service-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - order-internal

  order-redis:
    image: redis:7
    container_name: order-service-redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - order-internal

volumes:
  postgres_data:
  redis_data:

networks:
  inno-net:
    external: true
  order-internal:
    driver: bridge