spring:
  application:
    name: order-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

user-service:
  base-url: ${USER_SERVICE_URL}
  timeout-ms: 5000

server:
  port: ${SERVER_PORT:8082}