spring:

  application:
    name: inno-order-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6381

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI:http://localhost:8082/.well-known/jwks.json}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

payment:
  kafka:
    topic: ${PAYMENT_EVENTS_TOPIC:payment-events}
    consumer-group-id: ${PAYMENT_EVENTS_GROUP_ID:order-service-payment-events}

user-service:
  base-url: ${USER_SERVICE_URL:http://localhost:8081}
  timeout-ms: 5000

server:
  port: ${SERVER_PORT:8083}